//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class BoletaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto BoletaEntities usando la cadena de conexión encontrada en la sección 'BoletaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public BoletaEntities() : base("name=BoletaEntities", "BoletaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BoletaEntities.
        /// </summary>
        public BoletaEntities(string connectionString) : base(connectionString, "BoletaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto BoletaEntities.
        /// </summary>
        public BoletaEntities(EntityConnection connection) : base(connection, "BoletaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Boleta> Boleta
        {
            get
            {
                if ((_Boleta == null))
                {
                    _Boleta = base.CreateObjectSet<Boleta>("Boleta");
                }
                return _Boleta;
            }
        }
        private ObjectSet<Boleta> _Boleta;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Boleta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBoleta(Boleta boleta)
        {
            base.AddObject("Boleta", boleta);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BoletaModel", Name="Boleta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Boleta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Boleta.
        /// </summary>
        /// <param name="iD_Boleta">Valor inicial de la propiedad ID_Boleta.</param>
        public static Boleta CreateBoleta(global::System.Int32 iD_Boleta)
        {
            Boleta boleta = new Boleta();
            boleta.ID_Boleta = iD_Boleta;
            return boleta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Boleta
        {
            get
            {
                return _ID_Boleta;
            }
            set
            {
                if (_ID_Boleta != value)
                {
                    OnID_BoletaChanging(value);
                    ReportPropertyChanging("ID_Boleta");
                    _ID_Boleta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Boleta");
                    OnID_BoletaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Boleta;
        partial void OnID_BoletaChanging(global::System.Int32 value);
        partial void OnID_BoletaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Terminal
        {
            get
            {
                return _Terminal;
            }
            set
            {
                OnTerminalChanging(value);
                ReportPropertyChanging("Terminal");
                _Terminal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Terminal");
                OnTerminalChanged();
            }
        }
        private Nullable<global::System.Int32> _Terminal;
        partial void OnTerminalChanging(Nullable<global::System.Int32> value);
        partial void OnTerminalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> hora
        {
            get
            {
                return _hora;
            }
            set
            {
                OnhoraChanging(value);
                ReportPropertyChanging("hora");
                _hora = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("hora");
                OnhoraChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _hora;
        partial void OnhoraChanging(Nullable<global::System.TimeSpan> value);
        partial void OnhoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> medio_pago
        {
            get
            {
                return _medio_pago;
            }
            set
            {
                Onmedio_pagoChanging(value);
                ReportPropertyChanging("medio_pago");
                _medio_pago = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("medio_pago");
                Onmedio_pagoChanged();
            }
        }
        private Nullable<global::System.Int32> _medio_pago;
        partial void Onmedio_pagoChanging(Nullable<global::System.Int32> value);
        partial void Onmedio_pagoChanged();

        #endregion

    
    }

    #endregion

    
}
