//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ComandaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ComandaEntities usando la cadena de conexión encontrada en la sección 'ComandaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ComandaEntities() : base("name=ComandaEntities", "ComandaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ComandaEntities.
        /// </summary>
        public ComandaEntities(string connectionString) : base(connectionString, "ComandaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ComandaEntities.
        /// </summary>
        public ComandaEntities(EntityConnection connection) : base(connection, "ComandaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comanda> Comanda
        {
            get
            {
                if ((_Comanda == null))
                {
                    _Comanda = base.CreateObjectSet<Comanda>("Comanda");
                }
                return _Comanda;
            }
        }
        private ObjectSet<Comanda> _Comanda;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comanda. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComanda(Comanda comanda)
        {
            base.AddObject("Comanda", comanda);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ComandaModel", Name="Comanda")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comanda : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comanda.
        /// </summary>
        /// <param name="iD_Comanda">Valor inicial de la propiedad ID_Comanda.</param>
        public static Comanda CreateComanda(global::System.Int32 iD_Comanda)
        {
            Comanda comanda = new Comanda();
            comanda.ID_Comanda = iD_Comanda;
            return comanda;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Comanda
        {
            get
            {
                return _ID_Comanda;
            }
            set
            {
                if (_ID_Comanda != value)
                {
                    OnID_ComandaChanging(value);
                    ReportPropertyChanging("ID_Comanda");
                    _ID_Comanda = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Comanda");
                    OnID_ComandaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Comanda;
        partial void OnID_ComandaChanging(global::System.Int32 value);
        partial void OnID_ComandaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Pedido
        {
            get
            {
                return _Pedido;
            }
            set
            {
                OnPedidoChanging(value);
                ReportPropertyChanging("Pedido");
                _Pedido = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pedido");
                OnPedidoChanged();
            }
        }
        private Nullable<global::System.Int32> _Pedido;
        partial void OnPedidoChanging(Nullable<global::System.Int32> value);
        partial void OnPedidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detalle
        {
            get
            {
                return _detalle;
            }
            set
            {
                OndetalleChanging(value);
                ReportPropertyChanging("detalle");
                _detalle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detalle");
                OndetalleChanged();
            }
        }
        private global::System.String _detalle;
        partial void OndetalleChanging(global::System.String value);
        partial void OndetalleChanged();

        #endregion

    
    }

    #endregion

    
}
