//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Cuenta_ProdEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Cuenta_ProdEntities usando la cadena de conexión encontrada en la sección 'Cuenta_ProdEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public Cuenta_ProdEntities() : base("name=Cuenta_ProdEntities", "Cuenta_ProdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Cuenta_ProdEntities.
        /// </summary>
        public Cuenta_ProdEntities(string connectionString) : base(connectionString, "Cuenta_ProdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Cuenta_ProdEntities.
        /// </summary>
        public Cuenta_ProdEntities(EntityConnection connection) : base(connection, "Cuenta_ProdEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cuenta_Producto> Cuenta_Producto
        {
            get
            {
                if ((_Cuenta_Producto == null))
                {
                    _Cuenta_Producto = base.CreateObjectSet<Cuenta_Producto>("Cuenta_Producto");
                }
                return _Cuenta_Producto;
            }
        }
        private ObjectSet<Cuenta_Producto> _Cuenta_Producto;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cuenta_Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCuenta_Producto(Cuenta_Producto cuenta_Producto)
        {
            base.AddObject("Cuenta_Producto", cuenta_Producto);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Cuenta_ProdModel", Name="Cuenta_Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cuenta_Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cuenta_Producto.
        /// </summary>
        /// <param name="iD_Lista">Valor inicial de la propiedad ID_Lista.</param>
        public static Cuenta_Producto CreateCuenta_Producto(global::System.Int32 iD_Lista)
        {
            Cuenta_Producto cuenta_Producto = new Cuenta_Producto();
            cuenta_Producto.ID_Lista = iD_Lista;
            return cuenta_Producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Lista
        {
            get
            {
                return _ID_Lista;
            }
            set
            {
                if (_ID_Lista != value)
                {
                    OnID_ListaChanging(value);
                    ReportPropertyChanging("ID_Lista");
                    _ID_Lista = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Lista");
                    OnID_ListaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Lista;
        partial void OnID_ListaChanging(global::System.Int32 value);
        partial void OnID_ListaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Cuenta
        {
            get
            {
                return _Cuenta;
            }
            set
            {
                OnCuentaChanging(value);
                ReportPropertyChanging("Cuenta");
                _Cuenta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cuenta");
                OnCuentaChanged();
            }
        }
        private Nullable<global::System.Int32> _Cuenta;
        partial void OnCuentaChanging(Nullable<global::System.Int32> value);
        partial void OnCuentaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> producto
        {
            get
            {
                return _producto;
            }
            set
            {
                OnproductoChanging(value);
                ReportPropertyChanging("producto");
                _producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("producto");
                OnproductoChanged();
            }
        }
        private Nullable<global::System.Int32> _producto;
        partial void OnproductoChanging(Nullable<global::System.Int32> value);
        partial void OnproductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                OnobservacionChanging(value);
                ReportPropertyChanging("observacion");
                _observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observacion");
                OnobservacionChanged();
            }
        }
        private global::System.String _observacion;
        partial void OnobservacionChanging(global::System.String value);
        partial void OnobservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private Nullable<global::System.Int32> _cantidad;
        partial void OncantidadChanging(Nullable<global::System.Int32> value);
        partial void OncantidadChanged();

        #endregion

    
    }

    #endregion

    
}
