//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class IngredientesEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto IngredientesEntities usando la cadena de conexión encontrada en la sección 'IngredientesEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public IngredientesEntities() : base("name=IngredientesEntities", "IngredientesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto IngredientesEntities.
        /// </summary>
        public IngredientesEntities(string connectionString) : base(connectionString, "IngredientesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto IngredientesEntities.
        /// </summary>
        public IngredientesEntities(EntityConnection connection) : base(connection, "IngredientesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Ingredientes> Ingredientes
        {
            get
            {
                if ((_Ingredientes == null))
                {
                    _Ingredientes = base.CreateObjectSet<Ingredientes>("Ingredientes");
                }
                return _Ingredientes;
            }
        }
        private ObjectSet<Ingredientes> _Ingredientes;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Ingredientes. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToIngredientes(Ingredientes ingredientes)
        {
            base.AddObject("Ingredientes", ingredientes);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IngredientesModel", Name="Ingredientes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredientes : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Ingredientes.
        /// </summary>
        /// <param name="iD_Ingredientes">Valor inicial de la propiedad ID_Ingredientes.</param>
        public static Ingredientes CreateIngredientes(global::System.Int32 iD_Ingredientes)
        {
            Ingredientes ingredientes = new Ingredientes();
            ingredientes.ID_Ingredientes = iD_Ingredientes;
            return ingredientes;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Ingredientes
        {
            get
            {
                return _ID_Ingredientes;
            }
            set
            {
                if (_ID_Ingredientes != value)
                {
                    OnID_IngredientesChanging(value);
                    ReportPropertyChanging("ID_Ingredientes");
                    _ID_Ingredientes = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Ingredientes");
                    OnID_IngredientesChanged();
                }
            }
        }
        private global::System.Int32 _ID_Ingredientes;
        partial void OnID_IngredientesChanging(global::System.Int32 value);
        partial void OnID_IngredientesChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> producto
        {
            get
            {
                return _producto;
            }
            set
            {
                OnproductoChanging(value);
                ReportPropertyChanging("producto");
                _producto = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("producto");
                OnproductoChanged();
            }
        }
        private Nullable<global::System.Int32> _producto;
        partial void OnproductoChanging(Nullable<global::System.Int32> value);
        partial void OnproductoChanged();

        #endregion

    
    }

    #endregion

    
}
