//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class mesaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto mesaEntities usando la cadena de conexión encontrada en la sección 'mesaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public mesaEntities() : base("name=mesaEntities", "mesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto mesaEntities.
        /// </summary>
        public mesaEntities(string connectionString) : base(connectionString, "mesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto mesaEntities.
        /// </summary>
        public mesaEntities(EntityConnection connection) : base(connection, "mesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Mesa> Mesa
        {
            get
            {
                if ((_Mesa == null))
                {
                    _Mesa = base.CreateObjectSet<Mesa>("Mesa");
                }
                return _Mesa;
            }
        }
        private ObjectSet<Mesa> _Mesa;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Mesa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMesa(Mesa mesa)
        {
            base.AddObject("Mesa", mesa);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MesaModel", Name="Mesa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mesa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Mesa.
        /// </summary>
        /// <param name="iD_Mesa">Valor inicial de la propiedad ID_Mesa.</param>
        public static Mesa CreateMesa(global::System.Int32 iD_Mesa)
        {
            Mesa mesa = new Mesa();
            mesa.ID_Mesa = iD_Mesa;
            return mesa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Mesa
        {
            get
            {
                return _ID_Mesa;
            }
            set
            {
                if (_ID_Mesa != value)
                {
                    OnID_MesaChanging(value);
                    ReportPropertyChanging("ID_Mesa");
                    _ID_Mesa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Mesa");
                    OnID_MesaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Mesa;
        partial void OnID_MesaChanging(global::System.Int32 value);
        partial void OnID_MesaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sector
        {
            get
            {
                return _sector;
            }
            set
            {
                OnsectorChanging(value);
                ReportPropertyChanging("sector");
                _sector = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sector");
                OnsectorChanged();
            }
        }
        private Nullable<global::System.Int32> _sector;
        partial void OnsectorChanging(Nullable<global::System.Int32> value);
        partial void OnsectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private Nullable<global::System.Int32> _estado;
        partial void OnestadoChanging(Nullable<global::System.Int32> value);
        partial void OnestadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> llegada
        {
            get
            {
                return _llegada;
            }
            set
            {
                OnllegadaChanging(value);
                ReportPropertyChanging("llegada");
                _llegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llegada");
                OnllegadaChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _llegada;
        partial void OnllegadaChanging(Nullable<global::System.TimeSpan> value);
        partial void OnllegadaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> estadia
        {
            get
            {
                return _estadia;
            }
            set
            {
                OnestadiaChanging(value);
                ReportPropertyChanging("estadia");
                _estadia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estadia");
                OnestadiaChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _estadia;
        partial void OnestadiaChanging(Nullable<global::System.TimeSpan> value);
        partial void OnestadiaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> salida
        {
            get
            {
                return _salida;
            }
            set
            {
                OnsalidaChanging(value);
                ReportPropertyChanging("salida");
                _salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salida");
                OnsalidaChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _salida;
        partial void OnsalidaChanging(Nullable<global::System.TimeSpan> value);
        partial void OnsalidaChanged();

        #endregion

    
    }

    #endregion

    
}
