//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ProductosEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ProductosEntities usando la cadena de conexión encontrada en la sección 'ProductosEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ProductosEntities() : base("name=ProductosEntities", "ProductosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ProductosEntities.
        /// </summary>
        public ProductosEntities(string connectionString) : base(connectionString, "ProductosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ProductosEntities.
        /// </summary>
        public ProductosEntities(EntityConnection connection) : base(connection, "ProductosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> Producto
        {
            get
            {
                if ((_Producto == null))
                {
                    _Producto = base.CreateObjectSet<Producto>("Producto");
                }
                return _Producto;
            }
        }
        private ObjectSet<Producto> _Producto;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Producto. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProducto(Producto producto)
        {
            base.AddObject("Producto", producto);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProductosModel", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="iD_Producto">Valor inicial de la propiedad ID_Producto.</param>
        public static Producto CreateProducto(global::System.Int32 iD_Producto)
        {
            Producto producto = new Producto();
            producto.ID_Producto = iD_Producto;
            return producto;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Producto
        {
            get
            {
                return _ID_Producto;
            }
            set
            {
                if (_ID_Producto != value)
                {
                    OnID_ProductoChanging(value);
                    ReportPropertyChanging("ID_Producto");
                    _ID_Producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Producto");
                    OnID_ProductoChanged();
                }
            }
        }
        private global::System.Int32 _ID_Producto;
        partial void OnID_ProductoChanging(global::System.Int32 value);
        partial void OnID_ProductoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private Nullable<global::System.Int32> _precio;
        partial void OnprecioChanging(Nullable<global::System.Int32> value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> categoria
        {
            get
            {
                return _categoria;
            }
            set
            {
                OncategoriaChanging(value);
                ReportPropertyChanging("categoria");
                _categoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoria");
                OncategoriaChanged();
            }
        }
        private Nullable<global::System.Int32> _categoria;
        partial void OncategoriaChanging(Nullable<global::System.Int32> value);
        partial void OncategoriaChanged();

        #endregion

    
    }

    #endregion

    
}
