//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class Status_MesaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto Status_MesaEntities usando la cadena de conexión encontrada en la sección 'Status_MesaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public Status_MesaEntities() : base("name=Status_MesaEntities", "Status_MesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Status_MesaEntities.
        /// </summary>
        public Status_MesaEntities(string connectionString) : base(connectionString, "Status_MesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto Status_MesaEntities.
        /// </summary>
        public Status_MesaEntities(EntityConnection connection) : base(connection, "Status_MesaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Status_Mesa> Status_Mesa
        {
            get
            {
                if ((_Status_Mesa == null))
                {
                    _Status_Mesa = base.CreateObjectSet<Status_Mesa>("Status_Mesa");
                }
                return _Status_Mesa;
            }
        }
        private ObjectSet<Status_Mesa> _Status_Mesa;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Status_Mesa. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToStatus_Mesa(Status_Mesa status_Mesa)
        {
            base.AddObject("Status_Mesa", status_Mesa);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Status_MesaModel", Name="Status_Mesa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Status_Mesa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Status_Mesa.
        /// </summary>
        /// <param name="iD_estado">Valor inicial de la propiedad ID_estado.</param>
        public static Status_Mesa CreateStatus_Mesa(global::System.Int32 iD_estado)
        {
            Status_Mesa status_Mesa = new Status_Mesa();
            status_Mesa.ID_estado = iD_estado;
            return status_Mesa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_estado
        {
            get
            {
                return _ID_estado;
            }
            set
            {
                if (_ID_estado != value)
                {
                    OnID_estadoChanging(value);
                    ReportPropertyChanging("ID_estado");
                    _ID_estado = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_estado");
                    OnID_estadoChanged();
                }
            }
        }
        private global::System.Int32 _ID_estado;
        partial void OnID_estadoChanging(global::System.Int32 value);
        partial void OnID_estadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
    }

    #endregion

    
}
