//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ProyectBar.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class TerminalEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto TerminalEntities usando la cadena de conexión encontrada en la sección 'TerminalEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public TerminalEntities() : base("name=TerminalEntities", "TerminalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TerminalEntities.
        /// </summary>
        public TerminalEntities(string connectionString) : base(connectionString, "TerminalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto TerminalEntities.
        /// </summary>
        public TerminalEntities(EntityConnection connection) : base(connection, "TerminalEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Terminal> Terminal
        {
            get
            {
                if ((_Terminal == null))
                {
                    _Terminal = base.CreateObjectSet<Terminal>("Terminal");
                }
                return _Terminal;
            }
        }
        private ObjectSet<Terminal> _Terminal;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Terminal. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTerminal(Terminal terminal)
        {
            base.AddObject("Terminal", terminal);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TerminalModel", Name="Terminal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Terminal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Terminal.
        /// </summary>
        /// <param name="iD_Terminal">Valor inicial de la propiedad ID_Terminal.</param>
        public static Terminal CreateTerminal(global::System.Int32 iD_Terminal)
        {
            Terminal terminal = new Terminal();
            terminal.ID_Terminal = iD_Terminal;
            return terminal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Terminal
        {
            get
            {
                return _ID_Terminal;
            }
            set
            {
                if (_ID_Terminal != value)
                {
                    OnID_TerminalChanging(value);
                    ReportPropertyChanging("ID_Terminal");
                    _ID_Terminal = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Terminal");
                    OnID_TerminalChanged();
                }
            }
        }
        private global::System.Int32 _ID_Terminal;
        partial void OnID_TerminalChanging(global::System.Int32 value);
        partial void OnID_TerminalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sector
        {
            get
            {
                return _sector;
            }
            set
            {
                OnsectorChanging(value);
                ReportPropertyChanging("sector");
                _sector = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sector");
                OnsectorChanged();
            }
        }
        private Nullable<global::System.Int32> _sector;
        partial void OnsectorChanging(Nullable<global::System.Int32> value);
        partial void OnsectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();

        #endregion

    
    }

    #endregion

    
}
